import type { Metadata } from "next";
import { LegalDocument, type LegalSection } from "@/components/marketing/LegalDocument";

export const metadata: Metadata = {
  title: "Privacy Policy — Kettles",
  description:
    "How Kettles collects, uses, stores, and protects your personal data when you use our time-tracking product.",
  alternates: { canonical: "/legal/privacy" },
};

const LAST_UPDATED = "2026-08-09";

const sections: LegalSection[] = [
  {
    id: "introduction",
    title: "Introduction",
    body: (
      <>
        <p>
          Kettles (&quot;Kettles,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) provides task-linked time
          tracking and related tools for focused work (the &quot;Service&quot;). This Privacy Policy
          explains what information we collect, how we use it, and the choices you have.
        </p>
        <p>
          By creating an account or using the Service, you agree to this Privacy Policy. If you do
          not agree, please do not use the Service.
        </p>
      </>
    ),
  },
  {
    id: "information-we-collect",
    title: "Information we collect",
    body: (
      <>
        <p>We collect information in three ways: you provide it, it is generated by your use of the Service, and (limited) technical data from your device or browser.</p>
        <p><strong>Account information.</strong> When you sign up or sign in we collect:</p>
        <ul>
          <li>Email address and password (passwords are hashed by our auth provider; we never store them in plain text)</li>
          <li>Display name or profile details you choose to add</li>
          <li>Authentication session tokens needed to keep you signed in</li>
        </ul>
        <p><strong>Workspace content.</strong> To deliver the product we store the data you create, including:</p>
        <ul>
          <li>Clients, projects, tasks, tags, and related notes or billing fields</li>
          <li>Time sessions (start/end, duration, billable flags, and links to tasks or projects)</li>
          <li>Reports, exports, and shared report links you generate</li>
          <li>Reminders, preferences, and other settings you configure</li>
        </ul>
        <p><strong>Shared reports.</strong> If you create a public report share link, viewers may access the report data you chose to share. We may store a password hash (if you protect the link), expiry or revocation status, and anonymized viewer-session identifiers used only to measure unique views without inflating counts.</p>
        <p><strong>Device and usage data.</strong> We automatically collect limited technical information such as browser or app version, operating system, approximate region derived from network metadata, error logs, and product interaction events needed to keep the Service reliable. Theme and some UI preferences may be stored locally on your device (for example in local storage).</p>
        <p><strong>Communications.</strong> If you email us or contact support, we keep the content of that correspondence and related contact details so we can respond.</p>
      </>
    ),
  },
  {
    id: "how-we-use",
    title: "How we use information",
    body: (
      <>
        <p>We use personal information to:</p>
        <ul>
          <li>Provide, operate, and maintain the Service (accounts, sync, timers, reports, shares)</li>
          <li>Authenticate you and secure your workspace</li>
          <li>Sync data across web, desktop, and extension clients when you are signed in</li>
          <li>Send transactional messages (for example email confirmation, password reset, or important service notices)</li>
          <li>Diagnose bugs, monitor reliability, and improve product quality</li>
          <li>Enforce our Terms of Service and protect against abuse or fraud</li>
          <li>Comply with legal obligations</li>
        </ul>
        <p>
          We do <strong>not</strong> sell your personal information. We do not use your workspace
          content (tasks, clients, time entries, reports) to train third-party advertising models
          or to target you with third-party ads.
        </p>
      </>
    ),
  },
  {
    id: "legal-bases",
    title: "Legal bases (EEA/UK)",
    body: (
      <>
        <p>If you are in the European Economic Area or United Kingdom, we process personal data under these bases where applicable:</p>
        <ul>
          <li><strong>Contract</strong> — to provide the Service you signed up for</li>
          <li><strong>Legitimate interests</strong> — to secure, improve, and operate the Service in ways that do not override your rights</li>
          <li><strong>Consent</strong> — where we ask for it (and you may withdraw it at any time)</li>
          <li><strong>Legal obligation</strong> — where the law requires us to retain or disclose information</li>
        </ul>
      </>
    ),
  },
  {
    id: "sharing",
    title: "How we share information",
    body: (
      <>
        <p>We share information only as needed to run the Service:</p>
        <ul>
          <li>
            <strong>Infrastructure providers.</strong> We use trusted processors such as Supabase
            (authentication and database) and hosting/CDN providers to store and deliver the
            Service. They process data on our instructions under appropriate agreements.
          </li>
          <li>
            <strong>People you share with.</strong> If you create a report share link (optionally
            password-protected), anyone with the link can view the shared report until you revoke
            it or it expires.
          </li>
          <li>
            <strong>Legal and safety.</strong> We may disclose information if required by law, or
            to protect the rights, safety, or property of Kettles, our users, or others.
          </li>
          <li>
            <strong>Business transfers.</strong> If we are involved in a merger, acquisition, or
            asset sale, your information may transfer as part of that transaction, subject to this
            Policy or a successor policy with equivalent protections.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: "retention",
    title: "Data retention",
    body: (
      <>
        <p>
          We retain account and workspace data for as long as your account is active and as needed
          to provide the Service. If you delete data inside the product (for example a task or
          project), we remove it from active systems subject to normal backup cycles.
        </p>
        <p>
          If you request account deletion, we will delete or anonymize personal data associated
          with your account within a reasonable period, except where we must retain limited
          records for legal, security, or accounting reasons (for example fraud prevention or tax
          records). Shared report links you created will stop working once the underlying account
          data is removed or the share is revoked.
        </p>
      </>
    ),
  },
  {
    id: "security",
    title: "Security",
    body: (
      <>
        <p>
          We use industry-standard measures to protect your data, including encryption in transit
          (HTTPS/TLS), authentication via a managed identity provider, and database access
          controls such as row-level security so users can only access their own workspace data by
          default.
        </p>
        <p>
          No method of transmission or storage is 100% secure. You are responsible for keeping
          your password confidential and for activity under your account. Contact us immediately
          if you believe your account has been compromised.
        </p>
      </>
    ),
  },
  {
    id: "cookies",
    title: "Cookies and local storage",
    body: (
      <>
        <p>
          The Service uses cookies and similar technologies (including local storage) that are
          necessary for authentication, session continuity, theme preference, and core product
          features. We do not use third-party advertising cookies on the product app.
        </p>
        <p>
          You can control cookies through your browser settings. Disabling necessary cookies may
          prevent sign-in or break core functionality.
        </p>
      </>
    ),
  },
  {
    id: "your-rights",
    title: "Your rights and choices",
    body: (
      <>
        <p>Depending on where you live, you may have rights to:</p>
        <ul>
          <li>Access the personal data we hold about you</li>
          <li>Correct inaccurate data</li>
          <li>Delete your data or account</li>
          <li>Export or port your data</li>
          <li>Object to or restrict certain processing</li>
          <li>Withdraw consent where processing is based on consent</li>
        </ul>
        <p>
          You can update much of your information directly in the product. For access, export, or
          deletion requests, email{" "}
          <a href="mailto:privacy@kettles.app">privacy@kettles.app</a>. We may need to verify your
          identity before fulfilling a request. You may also have the right to lodge a complaint
          with your local data protection authority.
        </p>
      </>
    ),
  },
  {
    id: "children",
    title: "Children",
    body: (
      <p>
        The Service is not directed to children under 16 (or the minimum age required in your
        jurisdiction). We do not knowingly collect personal information from children. If you
        believe a child has provided us data, contact us and we will take appropriate steps to
        delete it.
      </p>
    ),
  },
  {
    id: "international",
    title: "International transfers",
    body: (
      <p>
        We may process and store information in the United States and other countries where our
        providers operate. When we transfer personal data internationally, we use appropriate
        safeguards required by applicable law (such as standard contractual clauses) where
        necessary.
      </p>
    ),
  },
  {
    id: "changes",
    title: "Changes to this policy",
    body: (
      <p>
        We may update this Privacy Policy from time to time. When we do, we will revise the
        &quot;Last updated&quot; date at the top of this page and, for material changes, provide
        additional notice (for example in-app or by email). Continued use of the Service after an
        update becomes effective constitutes acceptance of the revised policy.
      </p>
    ),
  },
  {
    id: "contact",
    title: "Contact",
    body: (
      <>
        <p>For privacy questions or requests:</p>
        <ul>
          <li>
            Email: <a href="mailto:privacy@kettles.app">privacy@kettles.app</a>
          </li>
          <li>
            Product site:{" "}
            <a href="https://kettles.app" target="_blank" rel="noopener noreferrer">
              kettles.app
            </a>
          </li>
        </ul>
      </>
    ),
  },
];

export default function PrivacyPolicyPage() {
  return (
    <LegalDocument
      title="Privacy Policy"
      description="How we collect, use, store, and protect personal data when you use Kettles."
      lastUpdated={LAST_UPDATED}
      sections={sections}
      relatedHref="/legal/terms"
      relatedLabel="Terms of Service"
    />
  );
}
